/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.my.graphql.webapp.example;

import org.junit.Test;

public class HelloServletTest {
    @Test public void testAppHasAGreeting() {
    }
}
